services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: mohammed
      POSTGRES_PASSWORD: superman
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chatatunedb
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5433
    networks:
      - chatatune
    restart: unless-stopped
  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - chatatune
    command:
      - "start-dev"
networks:
  chatatune:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local
